In [1]:
import pandas as pd

from sodapy import Socrata

In [2]:
client = Socrata("data.cityofnewyork.us", "w5ANkINfDguTjEbedyzkLA1HW")

results = client.get("5uac-w243", limit=3000)

crime_df = pd.DataFrame.from_records(results)
crime_df.head()

,cmplnt_num,addr_pct_cd,boro_nm,cmplnt_fr_dt,cmplnt_fr_tm,crm_atpt_cptd_cd,jurisdiction_code,juris_desc,ky_cd,law_cat_cd,...,cmplnt_to_dt,cmplnt_to_tm,susp_age_group,susp_race,susp_sex,hadevelopt,housing_psa,station_name,transit_district,parks_nm
0,797931560,33,MANHATTAN,2020-09-16T00:00:00.000,00:30:00,COMPLETED,0.0,N.Y. POLICE DEPT,112,FELONY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,664557183,32,MANHATTAN,2020-06-24T00:00:00.000,21:20:00,COMPLETED,0.0,N.Y. POLICE DEPT,344,MISDEMEANOR,...,2020-06-24T00:00:00.000,21:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,453437883,47,BRONX,2020-09-28T00:00:00.000,20:00:00,COMPLETED,0.0,N.Y. POLICE DEPT,105,FELONY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,949043828,43,BRONX,2020-07-26T00:00:00.000,01:08:00,COMPLETED,0.0,N.Y. POLICE DEPT,126,FELONY,...,NaN,NaN,18-24,WHITE,F,NaN,NaN,NaN,NaN,NaN
4,604509546,14,MANHATTAN,2020-09-26T00:00:00.000,19:30:00,COMPLETED,0.0,N.Y. POLICE DEPT,341,MISDEMEANOR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
crime_df_filtered = crime_df[["rpt_dt", "addr_pct_cd", "ofns_desc", "loc_of_occur_desc", "prem_typ_desc", "latitude", "longitude", "lat_lon"]].copy()

In [4]:
crime_df_filtered

,rpt_dt,addr_pct_cd,ofns_desc,loc_of_occur_desc,prem_typ_desc,latitude,longitude,lat_lon
0,2020-09-30T00:00:00.000,33,THEFT-FRAUD,INSIDE,RESIDENCE - APT. HOUSE,40.83730401400004,-73.94809867999999,"{'latitude': '40.83730401400004', 'longitude':..."
1,2020-06-24T00:00:00.000,32,ASSAULT 3 & RELATED OFFENSES,NaN,STREET,40.82413968200007,-73.94097291399999,"{'latitude': '40.82413968200007', 'longitude':..."
2,2020-09-29T00:00:00.000,47,ROBBERY,INSIDE,OTHER,40.88144124600007,-73.83235353999999,"{'latitude': '40.88144124600007', 'longitude':..."
3,2020-09-28T00:00:00.000,43,MISCELLANEOUS PENAL LAW,INSIDE,RESIDENCE-HOUSE,40.83527732600004,-73.85403335799998,"{'latitude': '40.83527732600004', 'longitude':..."
4,2020-09-27T00:00:00.000,14,PETIT LARCENY,NaN,STREET,40.75469651000003,-73.99535613299997,"{'latitude': '40.75469651000003', 'longitude':..."
...,...,...,...,...,...,...,...,...
2995,2020-09-29T00:00:00.000,71,PETIT LARCENY,INSIDE,DRUG STORE,40.66096989500005,-73.93136754499993,"{'latitude': '40.66096989500005', 'longitude':..."
2996,2020-09-30T00:00:00.000,106,PETIT LARCENY,REAR OF,STREET,40.683988597000045,-73.80679591999996,"{'latitude': '40.683988597000045', 'longitude'..."
2997,2020-09-28T00:00:00.000,47,ASSAULT 3 & RELATED OFFENSES,INSIDE,RESIDENCE - APT. HOUSE,40.87861210300008,-73.85732654999998,"{'latitude': '40.87861210300008', 'longitude':..."
2998,2020-09-28T00:00:00.000,75,OTHER OFFENSES RELATED TO THEF,FRONT OF,STREET,40.68778539600004,-73.86986475499998,"{'latitude': '40.68778539600004', 'longitude':..."
2999,2020-09-30T00:00:00.000,14,CRIMINAL MISCHIEF & RELATED OF,FRONT OF,HOMELESS SHELTER,40.75670745900004,-73.98449493899994,"{'latitude': '40.75670745900004', 'longitude':..."

In [5]:
crime_df_filtered = crime_df_filtered.dropna(subset=["lat_lon"])
crime_df_filtered

,rpt_dt,addr_pct_cd,ofns_desc,loc_of_occur_desc,prem_typ_desc,latitude,longitude,lat_lon
0,2020-09-30T00:00:00.000,33,THEFT-FRAUD,INSIDE,RESIDENCE - APT. HOUSE,40.83730401400004,-73.94809867999999,"{'latitude': '40.83730401400004', 'longitude':..."
1,2020-06-24T00:00:00.000,32,ASSAULT 3 & RELATED OFFENSES,NaN,STREET,40.82413968200007,-73.94097291399999,"{'latitude': '40.82413968200007', 'longitude':..."
2,2020-09-29T00:00:00.000,47,ROBBERY,INSIDE,OTHER,40.88144124600007,-73.83235353999999,"{'latitude': '40.88144124600007', 'longitude':..."
3,2020-09-28T00:00:00.000,43,MISCELLANEOUS PENAL LAW,INSIDE,RESIDENCE-HOUSE,40.83527732600004,-73.85403335799998,"{'latitude': '40.83527732600004', 'longitude':..."
4,2020-09-27T00:00:00.000,14,PETIT LARCENY,NaN,STREET,40.75469651000003,-73.99535613299997,"{'latitude': '40.75469651000003', 'longitude':..."
...,...,...,...,...,...,...,...,...
2995,2020-09-29T00:00:00.000,71,PETIT LARCENY,INSIDE,DRUG STORE,40.66096989500005,-73.93136754499993,"{'latitude': '40.66096989500005', 'longitude':..."
2996,2020-09-30T00:00:00.000,106,PETIT LARCENY,REAR OF,STREET,40.683988597000045,-73.80679591999996,"{'latitude': '40.683988597000045', 'longitude'..."
2997,2020-09-28T00:00:00.000,47,ASSAULT 3 & RELATED OFFENSES,INSIDE,RESIDENCE - APT. HOUSE,40.87861210300008,-73.85732654999998,"{'latitude': '40.87861210300008', 'longitude':..."
2998,2020-09-28T00:00:00.000,75,OTHER OFFENSES RELATED TO THEF,FRONT OF,STREET,40.68778539600004,-73.86986475499998,"{'latitude': '40.68778539600004', 'longitude':..."
2999,2020-09-30T00:00:00.000,14,CRIMINAL MISCHIEF & RELATED OF,FRONT OF,HOMELESS SHELTER,40.75670745900004,-73.98449493899994,"{'latitude': '40.75670745900004', 'longitude':..."

In [6]:
float(crime_df_filtered["lat_lon"][1]["longitude"])

-73.94097291399999

In [7]:
float(crime_df_filtered["lat_lon"][1]["latitude"])

40.82413968200007

In [8]:
crime_df_filtered["coords_list"] = crime_df_filtered[["latitude", "longitude"]].values.tolist()

crime_df_filtered

,rpt_dt,addr_pct_cd,ofns_desc,loc_of_occur_desc,prem_typ_desc,latitude,longitude,lat_lon,coords_list
0,2020-09-30T00:00:00.000,33,THEFT-FRAUD,INSIDE,RESIDENCE - APT. HOUSE,40.83730401400004,-73.94809867999999,"{'latitude': '40.83730401400004', 'longitude':...","[40.83730401400004, -73.94809867999999]"
1,2020-06-24T00:00:00.000,32,ASSAULT 3 & RELATED OFFENSES,NaN,STREET,40.82413968200007,-73.94097291399999,"{'latitude': '40.82413968200007', 'longitude':...","[40.82413968200007, -73.94097291399999]"
2,2020-09-29T00:00:00.000,47,ROBBERY,INSIDE,OTHER,40.88144124600007,-73.83235353999999,"{'latitude': '40.88144124600007', 'longitude':...","[40.88144124600007, -73.83235353999999]"
3,2020-09-28T00:00:00.000,43,MISCELLANEOUS PENAL LAW,INSIDE,RESIDENCE-HOUSE,40.83527732600004,-73.85403335799998,"{'latitude': '40.83527732600004', 'longitude':...","[40.83527732600004, -73.85403335799998]"
4,2020-09-27T00:00:00.000,14,PETIT LARCENY,NaN,STREET,40.75469651000003,-73.99535613299997,"{'latitude': '40.75469651000003', 'longitude':...","[40.75469651000003, -73.99535613299997]"
...,...,...,...,...,...,...,...,...,...
2995,2020-09-29T00:00:00.000,71,PETIT LARCENY,INSIDE,DRUG STORE,40.66096989500005,-73.93136754499993,"{'latitude': '40.66096989500005', 'longitude':...","[40.66096989500005, -73.93136754499993]"
2996,2020-09-30T00:00:00.000,106,PETIT LARCENY,REAR OF,STREET,40.683988597000045,-73.80679591999996,"{'latitude': '40.683988597000045', 'longitude'...","[40.683988597000045, -73.80679591999996]"
2997,2020-09-28T00:00:00.000,47,ASSAULT 3 & RELATED OFFENSES,INSIDE,RESIDENCE - APT. HOUSE,40.87861210300008,-73.85732654999998,"{'latitude': '40.87861210300008', 'longitude':...","[40.87861210300008, -73.85732654999998]"
2998,2020-09-28T00:00:00.000,75,OTHER OFFENSES RELATED TO THEF,FRONT OF,STREET,40.68778539600004,-73.86986475499998,"{'latitude': '40.68778539600004', 'longitude':...","[40.68778539600004, -73.86986475499998]"
2999,2020-09-30T00:00:00.000,14,CRIMINAL MISCHIEF & RELATED OF,FRONT OF,HOMELESS SHELTER,40.75670745900004,-73.98449493899994,"{'latitude': '40.75670745900004', 'longitude':...","[40.75670745900004, -73.98449493899994]"

In [9]:
crime_df_filtered.to_csv("NYC_crime.csv")